### PR TITLE
Implementation of issue #14

### LINKED ISSUE #14: Generate Access Token by validating TOTP challenge and if the machine is active
Accounts POST /machine/ABC123/token
IN totp
OUT machinePort=23433 
OUT token=BBCCCHHH3333

TOKEN=
- scope: machine-ABC123 localFw-127.0.0.1:23433

When TOTP is used only localFw is enabled because it is mean't to be used by the client side

### PR DESCRIPTION
**Pull request by jairsjunior**
Add of POST /machine/:machineId/token with TOTP code to retrieve port and jwt token for conection.

POST Body
`{ "code": "999999" }`

RESPONSE Body
`{"machinePort":"18159","token":"eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhaWQiOiIxNjQ0NTQ0NzAwMDEwNCIsInJmdyI6ImxvY2FsaG9zdDoxODE1OSIsImxmdyI6ImxvY2FsaG9zdDozMzg5Iiwic3ViIjoiTEpHODMyMiIsInB0eSI6ImZhbHNlIiwianRpIjoiODZjM2ZiYjUtN2Q1My00Yzc1LTk2OTMtZDc4MWJhNzVkY2Q5IiwiaWF0IjoxNTg0OTk4NTI2LCJleHAiOjE1ODUwMDIxMjYsImF1ZCI6ImxvY2FsaG9zdDo5OTk5IiwiaXNzIjoiQ29udmlkRG9ja2VyIn0.aC3yp-KrK0sOKbaHmhrNkwwBDxnK2OXbZh7qYOXy8GG7Y1qhjprQddhSaLWl980L9cheeJyh7hFmhyrz8yiO-vSSDTE1D59YO_UqXuIc-PUcUuvacgBhDkmX_FYDtItyouD1MQrXN1O2d_nXE-iNeNBEG_q9lvGr7lxkddlsW64"}`

Close #14

### CODE REVIEW

**Comment by tiagostutz** [comment]
Is the TOTP mandatory or can it be configured in the build to generate a version that doesn't use it, using just the MachineID/AccountID?

I'm asking because although this is more secure, this can be a challenge for some users. 

What are the risks if the user opts for a non-TOTP solution?

**Comment by jairsjunior** [comment]
Hi @tiagostutz!

I'm glad that you asking this. The project already had a environment variable WITH_TOTP but i did't added this validation on the first commit, now i added had this validation.

About the risk, it's one more factor of authentication that increase the security of this tunnel connection, if the customer lose ou share his accountId and machineId, another person cannot connect without the code that changes every 30 seconds.

**Comment by tiagostutz** [comment]
Got it... 
About getting the MachineID and AccountID to connect on the users machine I'm not that afraid because the attacker would have to know the Windows User/Pass also. My main concern is about the attacker being able to listen to another users connections and ports of sessions that are running on the same server... is this risk addresses by the JWT solution or is this issue not covered yet?

**Comment by jairsjunior** [comment]
This risk is addressed with JWT solution that is already implemented, but to use this, we need to implement another issues at the agent project and change the ssh-server for this one https://github.com/flaviostutz/ssh-jwt

**Comment by tiagostutz** [comment]
Sweet!  Sounds good to me.
Accepting now.

**Pull request merged**
